# Generated by Django 3.2.7 on 2022-09-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-nw_publish',)},
        ),
    ]
