# Generated by Django 3.2.7 on 2022-09-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_news_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='nw_slug',
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True, unique_for_date='nw_publish'),
        ),
    ]
