# Generated by Django 3.2.7 on 2022-09-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220903_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
    ]
