# Generated by Django 3.2.7 on 2022-05-21 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rp_body', models.TextField()),
            ],
        ),
    ]
