# Generated by Django 3.2.7 on 2022-09-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_news_image_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(max_length=300, verbose_name='Slug'),
        ),
    ]
