# Generated by Django 3.2.7 on 2022-05-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_reports_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='rp_body',
        ),
    ]
