# Generated by Django 3.2.7 on 2022-09-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_name', models.CharField(max_length=500)),
                ('mm_position', models.CharField(max_length=400)),
                ('mm_image', models.ImageField(unique=True, upload_to='')),
            ],
            options={
                'ordering': ('mm_name',),
            },
        ),
    ]
