# Generated by Django 3.2.7 on 2022-09-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220923_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=300, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(max_length=300, unique_for_date='publish'),
        ),
    ]
