# Generated by Django 3.2.7 on 2022-09-23 13:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
