# Generated by Django 3.2.7 on 2022-09-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_news_news_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('nw_publish',)},
        ),
    ]
