# Generated by Django 3.2.7 on 2022-09-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=300, unique_for_date='nw_publish'),
        ),
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(max_length=300, unique_for_date='date'),
        ),
    ]
