# Generated by Django 3.2.7 on 2022-09-23 15:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220923_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
