# Generated by Django 3.2.7 on 2022-09-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_news_news_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_header',
            field=models.ImageField(null=True, unique=True, upload_to=''),
        ),
    ]
