# Generated by Django 3.2.7 on 2022-09-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_news_image_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
