# Generated by Django 3.2.7 on 2022-09-23 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_news_image_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=300, unique_for_date='date')),
                ('url', models.URLField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('pr_title',),
            },
        ),
    ]
