# Generated by Django 3.2.7 on 2022-09-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_slug_report_rp_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='rp_slug',
            new_name='slug',
        ),
    ]
