# Generated by Django 3.2.7 on 2022-09-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_header',
        ),
    ]
