# Generated by Django 3.2.7 on 2022-09-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_news_image_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_header',
            field=models.ImageField(default='', upload_to='featured_image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
