# Generated by Django 3.2.7 on 2022-09-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_news_image_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to='featured_image/%Y/%m/%d/'),
        ),
    ]
