# Generated by Django 3.2.7 on 2023-04-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_news_news_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_w', models.PositiveIntegerField(default=250)),
                ('img_h', models.PositiveIntegerField(default=413)),
                ('photo', models.ImageField(height_field='img_h', upload_to=None, width_field='img_w')),
            ],
        ),
    ]
