# Generated by Django 3.2.7 on 2023-04-12 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('p_date',)},
        ),
        migrations.AddField(
            model_name='gallery',
            name='p_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gallery',
            name='p_slug',
            field=models.SlugField(default='1', max_length=300, unique_for_date='p_date'),
        ),
    ]
