# Generated by Django 3.2.7 on 2023-04-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20230412_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='p_caption',
            field=models.CharField(default='photo', max_length=500),
        ),
    ]
