# Generated by Django 3.2.7 on 2023-04-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_gallery_p_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='photo',
            new_name='ph',
        ),
    ]
