# Generated by Django 3.2.7 on 2023-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_rename_photo_gallery_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_img_h',
            field=models.PositiveIntegerField(default=167),
        ),
        migrations.AddField(
            model_name='news',
            name='news_img_w',
            field=models.PositiveIntegerField(default=270),
        ),
    ]
