# Generated by Django 3.2.7 on 2023-04-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20230428_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_img_h',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_img_w',
        ),
    ]
