# Generated by Django 3.2.7 on 2023-04-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20230428_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_img_h',
            field=models.PositiveIntegerField(default=167),
        ),
        migrations.AddField(
            model_name='news',
            name='news_img_w',
            field=models.PositiveIntegerField(default=270),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_header',
            field=models.ImageField(blank=True, height_field='news_img_h', null=True, upload_to='featured_image/%Y/%m/%d/', width_field='news_img_w'),
        ),
    ]
