# Generated by Django 3.2.7 on 2023-05-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vid_title',
            field=models.CharField(default='one', max_length=500),
        ),
    ]
