# Generated by Django 3.2.7 on 2023-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_video_vid_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
