# Generated by Django 3.2.7 on 2023-05-09 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_fc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='rp_tags',
            new_name='tags',
        ),
    ]
