# Generated by Django 3.2.7 on 2023-05-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_rename_rp_tags_report_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_tags',
            new_name='tags',
        ),
    ]
