# Generated by Django 3.2.7 on 2023-11-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_rename_news_tags_news_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FC',
            new_name='NewList',
        ),
    ]
