# Generated by Django 3.2.7 on 2023-11-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_rename_fc_newlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_list', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=300, unique_for_date='date')),
                ('url', models.URLField(max_length=500)),
            ],
        ),
    ]
