# Generated by Django 3.2.7 on 2023-11-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_flist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flist',
            name='c_list',
        ),
        migrations.RemoveField(
            model_name='flist',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='flist',
            name='url',
        ),
    ]
