# Generated by Django 3.2.7 on 2023-11-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20231129_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flist',
            options={'ordering': ('f_list',)},
        ),
        migrations.AddField(
            model_name='flist',
            name='date',
            field=models.CharField(default='date', max_length=100),
        ),
        migrations.AddField(
            model_name='flist',
            name='f_list',
            field=models.CharField(default='former', max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='flist',
            name='slug',
            field=models.SlugField(default='slug', max_length=300, unique_for_date='date'),
        ),
        migrations.AddField(
            model_name='flist',
            name='url',
            field=models.URLField(default='url', max_length=500),
        ),
    ]
