# Generated by Django 3.2.7 on 2023-12-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20231130_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flist',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='flist',
            name='url',
        ),
        migrations.AddField(
            model_name='flist',
            name='pdf_file',
            field=models.FileField(default='pdf', upload_to='pdfs/'),
        ),
    ]
