# Generated by Django 3.2.7 on 2023-12-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20231203_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='report',
            name='url',
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(default='pdf', upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.CharField(default='date', max_length=100),
        ),
    ]
