# Generated by Django 3.2.7 on 2023-12-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_alter_report_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newlist',
            options={'ordering': ('mem_name',)},
        ),
        migrations.AddField(
            model_name='newlist',
            name='faith',
            field=models.CharField(default='faith', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='newlist',
            name='mem_name',
            field=models.CharField(default='new', max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='newlist',
            name='position',
            field=models.CharField(default='position', max_length=500, unique=True),
        ),
    ]
