# Generated by Django 3.2.7 on 2023-12-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20231222_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlist',
            name='faith',
            field=models.CharField(default='faith', max_length=50),
        ),
        migrations.AlterField(
            model_name='newlist',
            name='position',
            field=models.CharField(default='position', max_length=500),
        ),
    ]
