# Generated by Django 3.2.7 on 2023-12-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_auto_20231222_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlist',
            name='faith',
            field=models.CharField(blank=True, default='faith', max_length=50),
        ),
        migrations.AlterField(
            model_name='newlist',
            name='mem_name',
            field=models.CharField(blank=True, default='new', max_length=500, unique=True),
        ),
    ]
