# Generated by Django 3.2.7 on 2023-12-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_alter_newlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newlist',
            options={'ordering': ['order', 'mem_name']},
        ),
        migrations.AddField(
            model_name='newlist',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
