# Generated by Django 3.2.7 on 2023-12-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_auto_20231222_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newlist',
            options={'ordering': ['order', 'position']},
        ),
    ]
